### ISSUE TITLE
Receive RGB Data on Arduino?

### ISSUE THREAD

**Issue by Jestopher** [arneboe/starArduino#1]
Is there something in here that will receive WS2811 data on arduino?  I couldn't tell from the files I looked through - but if you could point me to an example code that would be awesome!

**Comment by arneboe** [comment]
What do you mean by "WS2811 data"? Do you want to receive the ws2811 protocol and do something with it? I.e. the protocol that the leds speak?  Or do you want to receive rgb data and forward it to ws2811 leds?
